# -*- coding: utf-8 -*-
"""Project 138.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vx5HUAw7Z2qXDeq6UM_fK-cMSufF6lXt
"""

!pip install kaggle

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop

!unzip articles-sharing-reading-from-cit-deskdrop.zip

import pandas as pd
import numpy as np

df_shared_articles = pd.read_csv("shared_articles.csv")
df_users_interactions = pd.read_csv("users_interactions.csv")

df_shared_articles.head()

df_users_interactions.head()